### ISSUE TITLE
Notify channel when office hours have started/ended

### ISSUE THREAD

**Issue by rorochaudhary** [beaver-hours/BeaverHours#26]
As a user, I would like to be notified in Teams when an office hours session has started or ended.

**Comment by richardcoucoules** [comment]
In our research on the bot last week, we found a core blockers for this feature to make sense: the `createConversationAsync` method required to generate a proactive (i.e., unprompted) message is not implemented in the Teams TypeScript library. This means that for a professor to start an office hour in a way that would notify the appropriate channel, the professor must send a message in that channel. In that way, the professor is already notifying the channel, making a bot notification redundant. I would recommend closing this issue for now, as this is dependent on an update in the Teams library, which is out of our control.

**Comment by rorochaudhary** [comment]
I agree with this evaluation of the current situation based on our team conversations as well. Should an alternative solution come up to notifying others that can be implemented on our end, we will open up a fresh issue instead. Will close.
